/**
 * Default pinned announcements — seeded into data/pinned-blog-posts.json
 * when empty. Editable from Admin → Blog.
 */
export const PINNED_BLOG_DEFAULTS = [
  {
    id: "pinned-website-inquiries",
    category: "Announcement",
    dateISO: "2026-08-09",
    title: "Website Inquiries Are Open — Plus Seven Spines in the Storm",
    body:
      "We’ve added a clear path for custom website builds. If you want a site designed, use Contact and choose Website build inquiry — those messages arrive tagged [WEBSITE INQUIRY] in the studio inbox.\n\nReach us at silverspinestudio.com/contact?topic=sites or email contact@silverspinestudio.com. Book launch still comes first — projects are considered by inquiry, fit, and timing.",
    bullets: [],
    mediaType: "video",
    mediaUrl: "/covers/seven-spines-noir-window.mp4",
    mediaPoster: "/covers/seven-spines-noir-window.png",
    mediaCaption: "Cream to deep fire red · seven spines in the storm",
    videoLive: true,
    figureKey: "",
    expandBody: "",
    actions: ["contact-sites", "books"],
    published: true,
    sortOrder: 50,
  },
  {
    id: "pinned-site-live",
    category: "Announcement",
    dateISO: "2026-08-08",
    title: "Silver Spine Studio™ Is Live — Come On In",
    body:
      "The site is in production. Rain, lightning, Books, Shop, Reviews, and the launch list are open — the storm is no longer waiting behind a closed gate.",
    bullets: [
      "Extended Sneak Peek is live in stores",
      "ARC list closed — the 25 Lucky Sleuthers have been notified",
      "3 lucky winners will each receive a FULL digital copy — join the launch list",
    ],
    mediaType: "figure",
    mediaUrl: "",
    mediaPoster: "",
    mediaCaption: "",
    figureKey: "cover",
    expandBody: "",
    actions: ["launch-list", "shop", "arc"],
    published: true,
    sortOrder: 40,
  },
  {
    id: "pinned-launch-timeline",
    category: "Announcement",
    dateISO: "2026-07-28",
    title: "The Beautiful Beast — Launch Timeline & What’s Next",
    body:
      "The road to release is mapped. Here’s the plan and how to get early access.",
    bullets: [
      "ARC sign-ups + selection window",
      "Cover reveal + teaser trailer",
      "Gumroad Insider Deal Oct 22 · official release Nov 1",
    ],
    mediaType: "figure",
    mediaUrl: "",
    mediaPoster: "",
    mediaCaption: "",
    figureKey: "arcQuote",
    expandBody:
      "Milestones\n\n1. Cover Reveal — Aug 3, 2026. The blank ribbon falls away. The premium artwork is officially unmasked.\n2. Sneak Peek Release — Aug 4, 2026. Digital Extended Sneak Peek (Prologue & Chapters 1–2) for $4.99 — live in stores. This purchase places you on the Insider Deal whitelist.\n3. ARC Sign-ups — Aug 7 – Aug 14, 2026. Window closed. The 25 Lucky Sleuthers have been chosen and notified (Aug 17).\n4. Teaser Trailer 2 Drop — Aug 21, 2026. Production loops push live.\n5. ARC Sneak Peek delivery — Oct 1–3, 2026. Prologue & Chapters 1–2 only — not the full novel.\n6. Launch Week Events — Oct 21–28, 2026. Site announcements and socials.\n7. Gumroad Insider Deal — Oct 22, 2026. $14.99 for whitelisted readers. The full DIGITAL file is not ready until Nov 1.\n8. Official Release Day — Nov 1, 2026. Full digital file · paperback $24.99 · hardcover $29.99 · digital retail $19.99.\n\nA note for readers & gift-givers\n\n• Begin with the Sneak Peek: $4.99 for Prologue & Chapters 1–2 — already in stores — and your place on the Insider whitelist.\n• Full DIGITAL: Gumroad Insider Deal Oct 22 at $14.99; the file arrives Nov 1 with the hardcover. Then $19.99 from Nov 1, 2026. Paperback $24.99. Hardcover $29.99 from Nov 1, 2026.\n• Holiday timing: Nov 1 release lands just as gift season begins — a Colorado thriller ready for the nightstand, the stocking, or the reader who loves a storm.",
    expandLabel: "View timeline",
    actions: ["timeline-toggle", "launch-list", "arc"],
    published: true,
    sortOrder: 30,
  },
  {
    id: "pinned-brand-look",
    category: "Behind the Scenes",
    dateISO: "2026-07-16",
    title: "Building the Silver Spine Look",
    body: "Jet black, deep gold, stormlight. The system we’re shipping across the site.",
    bullets: [],
    mediaType: "figure",
    mediaUrl: "",
    mediaPoster: "",
    mediaCaption: "",
    figureKey: "cliffside",
    expandBody:
      "Palette: Jet black base, storm-gold accents (#a77a23).\n\nType: Elegant serif for headings; clean sans for UI.\n\nMotion: Subtle fades/parallax under 400ms; cinematic, not busy.",
    expandLabel: "View notes",
    actions: ["brand-notes-toggle", "press"],
    published: true,
    sortOrder: 20,
  },
  {
    id: "pinned-chronicle-begins",
    category: "Announcement",
    dateISO: "2026-07-05",
    title: "The Seven-Fold Chronicle Begins",
    body:
      "Book One — The Beautiful Beast — opens the mapped sequence: thrillers forged in storm and consequence, where beauty and danger share the same breath.",
    bullets: [
      "Colorado highway. Thanksgiving night. The storm is already waiting.",
      "Future volumes follow the rolling narrative timeline after Book 1",
      "Join the launch list for calendar locks as dates firm up",
    ],
    mediaType: "figure",
    mediaUrl: "",
    mediaPoster: "",
    mediaCaption: "",
    figureKey: "highway",
    expandBody: "",
    actions: ["books", "launch-list"],
    published: true,
    sortOrder: 10,
  },
];
